name: deploy to lambda
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [14.*]
    runs-on: ubuntu-latest
    env:
      # AWS_DEFAULT_REGION: us-east-1
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2
      TF_VAR_master_password: ${{ secrets.TF_VAR_master_password }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build semantic-release
        run: |
          npm ci
          npm run build --if-present
          npx semantic-release
          # cat version.txt
          LATEST_VERSION=$(cat version.txt)
        env:
          CI: true
      - name: zip
        run: |
          echo $LATEST_VERSION
          cd dist
          zip -r ../location-service.zip .

      - name: default deploy
        run: |
          aws lambda update-function-code --function-name  location-service --zip-file fileb://location-service.zip